#!/usr/bin/env node

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { networkInterfaces } from 'node:os';
import * as z from 'zod/v4';
import {
  generateQrCode,
  scanQrCode,
} from './qr.js';
import {
  DEFAULT_MAX_CONTENT_CHARS,
  ENABLE_JINA_FALLBACK,
  captureWebPageToImages,
  fetchWebPage,
  fetchYouTubeTranscript,
  searchAndFetch,
  searchWeb,
} from './web.js';

const server = new McpServer({
  name: 'local-web-mcp',
  version: '0.1.0',
});

const IMAGE_DATA_URL_FALLBACK_MAX_CHARS = 30_000;
const ASSET_TTL_MS = parseInteger(process.env.LM_WEB_MCP_ASSET_TTL_MS, 24 * 60 * 60 * 1000);
const ASSET_PORT = parseInteger(process.env.LM_WEB_MCP_ASSET_PORT, 8765);
const ASSET_HOST = process.env.LM_WEB_MCP_ASSET_HOST ?? '0.0.0.0';
const ASSET_ROUTE_PREFIX = '/local-web-assets/';
const imageAssets = new Map();
let assetServerPromise = null;

const searchResultSchema = z.object({
  index: z.number(),
  title: z.string(),
  url: z.string(),
  snippet: z.string(),
  publishedAt: z.string().nullable(),
});

const pageSchema = z.object({
  url: z.string(),
  finalUrl: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  publishedTime: z.string().nullable(),
  contentType: z.string().nullable(),
  sourceMethod: z.string(),
  truncated: z.boolean(),
  text: z.string(),
  warning: z.string().nullable().optional(),
});

const screenshotImageSchema = z.object({
  index: z.number(),
  mimeType: z.string(),
  width: z.number().nullable(),
  height: z.number().nullable(),
  pageX: z.number(),
  pageY: z.number(),
  pageWidth: z.number(),
  pageHeight: z.number(),
  sizeBytes: z.number(),
  assetUrl: z.string().nullable().optional(),
});

const pageScreenshotsSchema = z.object({
  url: z.string(),
  finalUrl: z.string(),
  title: z.string(),
  viewportWidth: z.number(),
  viewportHeight: z.number(),
  fullPage: z.boolean(),
  pageWidth: z.number(),
  pageHeight: z.number(),
  capturedHeight: z.number(),
  format: z.string(),
  images: z.array(screenshotImageSchema),
  warning: z.string().nullable().optional(),
});

const youtubeTranscriptSchema = z.object({
  videoId: z.string(),
  url: z.string(),
  title: z.string(),
  channel: z.string().nullable(),
  thumbnailUrl: z.string().nullable(),
  language: z.string().nullable(),
  trackName: z.string(),
  isAutoGenerated: z.boolean(),
  segmentCount: z.number(),
  truncated: z.boolean(),
  text: z.string(),
});

const qrGenerateSchema = z.object({
  text: z.string(),
  mimeType: z.string(),
  imageBase64: z.string(),
  assetUrl: z.string().nullable().optional(),
  width: z.number(),
  height: z.number(),
  sizeBytes: z.number(),
  errorCorrectionLevel: z.string(),
  margin: z.number(),
});

const qrScanLocationPointSchema = z.object({
  x: z.number(),
  y: z.number(),
});

const qrScanSchema = z.object({
  text: z.string(),
  source: z.string(),
  mimeType: z.string(),
  width: z.number(),
  height: z.number(),
  location: z
    .object({
      topLeft: qrScanLocationPointSchema,
      topRight: qrScanLocationPointSchema,
      bottomRight: qrScanLocationPointSchema,
      bottomLeft: qrScanLocationPointSchema,
    })
    .nullable(),
});

server.registerTool(
  'web_search',
  {
    title: 'Web Search',
    description:
      'Search the web and return result titles, URLs, snippets, and publish dates when available. Use this before opening full pages.',
    inputSchema: {
      query: z.string().min(1).describe('The search query to run.'),
      count: z.coerce
        .number()
        .int()
        .min(1)
        .max(10)
        .optional()
        .describe('How many search results to return. Default: 5.'),
      site: z.string().optional().describe('Optional domain filter such as "docs.python.org".'),
      countryCode: z
        .string()
        .min(2)
        .max(5)
        .optional()
        .describe('Search market like "us", "gb", or "de". Default: "us".'),
      language: z
        .string()
        .optional()
        .describe('Language hint like "en-US". Default: "en-US".'),
    },
    outputSchema: {
      query: z.string(),
      fullQuery: z.string(),
      backend: z.string(),
      market: z.object({
        countryCode: z.string(),
        language: z.string(),
      }),
      results: z.array(searchResultSchema),
    },
  },
  wrapTool(async (args) => {
    const result = await searchWeb(args);
    return {
      content: [{ type: 'text', text: result.text }],
      structuredContent: {
        query: result.query,
        fullQuery: result.fullQuery,
        backend: result.backend,
        market: result.market,
        results: result.results,
      },
    };
  }),
);

server.registerTool(
  'qr_generate',
  {
    title: 'QR Generate',
    description:
      'Generate a QR code PNG image from text, a URL, Wi-Fi config, contact card, or any other QR payload. Returns image content that clients can display in chat.',
    inputSchema: {
      text: z
        .string()
        .min(1)
        .max(4_000)
        .describe('Text or payload to encode into the QR code.'),
      errorCorrectionLevel: z
        .enum(['L', 'M', 'Q', 'H'])
        .optional()
        .describe('QR error correction level. Higher levels survive more damage but make denser codes. Default: M.'),
      margin: z.coerce
        .number()
        .int()
        .min(0)
        .max(16)
        .optional()
        .describe('Quiet-zone margin around the QR code modules. Default: 4.'),
      width: z.coerce
        .number()
        .int()
        .min(128)
        .max(2_048)
        .optional()
        .describe('PNG image width and height in pixels. Default: 768.'),
      darkColor: z
        .string()
        .optional()
        .describe('Dark module color as #RRGGBB or #RRGGBBAA. Default: black.'),
      lightColor: z
        .string()
        .optional()
        .describe('Light background color as #RRGGBB or #RRGGBBAA. Default: white.'),
    },
    outputSchema: qrGenerateSchema.shape,
  },
  wrapTool(async (args) => {
    const qr = await generateQrCode(args);
    const assetUrl = await publishImageAsset({
      base64: qr.data,
      mimeType: qr.mimeType,
      label: 'qr-code',
    });
    return {
      content: [
        {
          type: 'text',
          text: [
            `Generated QR code image (${qr.width}x${qr.height}, ${qr.sizeBytes} bytes).`,
            assetUrl ? `QR code image URL: ${assetUrl}` : null,
          ]
            .filter(Boolean)
            .join('\n'),
        },
        {
          type: 'image',
          data: qr.data,
          mimeType: qr.mimeType,
        },
        {
          type: 'text',
          text: `QR code data URL:\ndata:${qr.mimeType};base64,${qr.data}`,
        },
      ],
      structuredContent: {
        text: qr.text,
        mimeType: qr.mimeType,
        imageBase64: qr.data,
        assetUrl,
        width: qr.width,
        height: qr.height,
        sizeBytes: qr.sizeBytes,
        errorCorrectionLevel: qr.errorCorrectionLevel,
        margin: qr.margin,
      },
    };
  }),
);

server.registerTool(
  'qr_scan',
  {
    title: 'QR Scan',
    description:
      'Read a QR code from a PNG or JPEG image URL, local file path, data URL, or base64 image. Use only with images the user provided or explicitly asked to inspect.',
    inputSchema: {
      imageUrl: z
        .string()
        .optional()
        .describe('HTTP/HTTPS image URL or data:image/...;base64 URL containing a QR code.'),
      imagePath: z
        .string()
        .optional()
        .describe('Local PNG/JPEG file path containing a QR code. Use only when the user provides the path.'),
      imageBase64: z
        .string()
        .optional()
        .describe('Raw base64 image bytes, or a data:image/...;base64 URL.'),
      mimeType: z
        .string()
        .optional()
        .describe('Optional image MIME type when passing raw base64. Supported: image/png, image/jpeg.'),
    },
    outputSchema: qrScanSchema.shape,
  },
  wrapTool(async (args) => {
    const result = await scanQrCode(args);
    return {
      content: [
        {
          type: 'text',
          text: `QR code text:\n${result.text}`,
        },
      ],
      structuredContent: result,
    };
  }),
);

server.registerTool(
  'youtube_transcript',
  {
    title: 'YouTube Transcript',
    description:
      'Extract transcript/captions from a YouTube video URL or video id without launching a browser. Use this for YouTube summaries and question answering.',
    inputSchema: {
      url: z.string().optional().describe('A YouTube URL such as https://www.youtube.com/watch?v=...'),
      videoId: z.string().optional().describe('An 11-character YouTube video id.'),
      language: z
        .string()
        .optional()
        .describe('Preferred transcript language code such as "en" or "lt". Falls back to the best available track.'),
      includeTimestamps: z
        .boolean()
        .optional()
        .describe('Whether to include timestamps at the start of transcript lines. Default: true.'),
      maxChars: z.coerce
        .number()
        .int()
        .min(1_000)
        .max(30_000)
        .optional()
        .describe(`Maximum transcript characters to return. Default: ${DEFAULT_MAX_CONTENT_CHARS}.`),
    },
    outputSchema: youtubeTranscriptSchema.shape,
  },
  wrapTool(async (args) => {
    if (!args.url && !args.videoId) {
      throw new Error('Provide either url or videoId.');
    }

    const transcript = await fetchYouTubeTranscript(args);
    return {
      content: [{ type: 'text', text: transcript.formattedText }],
      structuredContent: {
        videoId: transcript.videoId,
        url: transcript.url,
        title: transcript.title,
        channel: transcript.channel,
        thumbnailUrl: transcript.thumbnailUrl,
        language: transcript.language,
        trackName: transcript.trackName,
        isAutoGenerated: transcript.isAutoGenerated,
        segmentCount: transcript.segmentCount,
        truncated: transcript.truncated,
        text: transcript.text,
      },
    };
  }),
);

server.registerTool(
  'web_fetch',
  {
    title: 'Web Fetch',
    description:
      'Download a single web page and return readable text content. Works for normal web pages and can fall back to a reader service for hard-to-parse pages.',
    inputSchema: {
      url: z.string().url().describe('The page URL to fetch.'),
      maxChars: z.coerce
        .number()
        .int()
        .min(1_000)
        .max(30_000)
        .optional()
        .describe(`Maximum characters of page text to return. Default: ${DEFAULT_MAX_CONTENT_CHARS}.`),
      preferReader: z
        .boolean()
        .optional()
        .describe(
          `Whether to use the reader fallback when direct extraction is weak or blocked. Default: true. Current server fallback enabled: ${ENABLE_JINA_FALLBACK}.`,
        ),
    },
    outputSchema: pageSchema.shape,
  },
  wrapTool(async (args) => {
    const page = await fetchWebPage(args);
    const content = [
      `Title: ${page.title}`,
      `URL: ${page.finalUrl}`,
      page.description ? `Description: ${page.description}` : null,
      page.publishedTime ? `Published: ${page.publishedTime}` : null,
      `Method: ${page.sourceMethod}`,
      page.warning ? `Warning: ${page.warning}` : null,
      '',
      page.text,
    ]
      .filter(Boolean)
      .join('\n');

    return {
      content: [{ type: 'text', text: content }],
      structuredContent: page,
    };
  }),
);

server.registerTool(
  'web_page_to_images',
  {
    title: 'Web Page To Images',
    description:
      'Load a web page in a browser and capture the rendered page as screenshot image content. Capture the full scrollable page by default; use fullPage=false only when the user explicitly asks for the top/current viewport. Tall full-page captures are split into multiple images.',
    inputSchema: {
      url: z.string().url().describe('The page URL to render and capture.'),
      viewportWidth: z.coerce
        .number()
        .int()
        .min(320)
        .max(3840)
        .optional()
        .describe('Browser viewport width in CSS pixels. Default: 1280.'),
      viewportHeight: z.coerce
        .number()
        .int()
        .min(320)
        .max(2160)
        .optional()
        .describe('Browser viewport height in CSS pixels. Default: 900.'),
      fullPage: z
        .boolean()
        .optional()
        .describe('Legacy option. Full-page capture is forced unless viewportOnly=true is also set. Default: true.'),
      viewportOnly: z
        .boolean()
        .optional()
        .describe('Set true only when the user explicitly asks for only the top/current visible viewport instead of the full scrollable page. Default: false.'),
      waitUntil: z
        .enum(['domcontentloaded', 'load', 'networkidle'])
        .optional()
        .describe('Page load state to wait for before capture. Default: networkidle.'),
      waitAfterLoadMs: z.coerce
        .number()
        .int()
        .min(0)
        .max(10_000)
        .optional()
        .describe('Extra wait after the selected load state, in milliseconds. Default: 1000.'),
      scrollToLoad: z
        .boolean()
        .optional()
        .describe('Whether to scroll through the page first to trigger lazy loading. Default: true.'),
      segmentHeight: z.coerce
        .number()
        .int()
        .min(1_000)
        .max(16_000)
        .optional()
        .describe('Maximum CSS-pixel height per returned screenshot image. Default: 10000.'),
      maxPageHeight: z.coerce
        .number()
        .int()
        .min(1_000)
        .max(100_000)
        .optional()
        .describe('Maximum full-page CSS-pixel height to capture. Default: 50000.'),
      format: z
        .enum(['png', 'jpeg'])
        .optional()
        .describe('Screenshot image format. Default: png.'),
      jpegQuality: z.coerce
        .number()
        .int()
        .min(1)
        .max(100)
        .optional()
        .describe('JPEG quality when format is jpeg. Default: 90.'),
    },
    outputSchema: pageScreenshotsSchema.shape,
  },
  wrapTool(async (args) => {
    const captureArgs = {
      ...args,
      fullPage: args.viewportOnly === true ? false : true,
    };
    delete captureArgs.viewportOnly;
    const result = await captureWebPageToImages(captureArgs);
    const imagesWithAssets = await Promise.all(
      result.images.map(async (image) => ({
        ...image,
        assetUrl: await publishImageAsset({
          base64: image.data,
          mimeType: image.mimeType,
          label: `web-page-to-images-${image.index}`,
        }),
      })),
    );
    const imageContent = imagesWithAssets.flatMap((image) => {
      const content = [
        {
          type: 'image',
          data: image.data,
          mimeType: image.mimeType,
        },
      ];

      if (image.assetUrl) {
        content.push({
          type: 'text',
          text: `Screenshot ${image.index} image URL: ${image.assetUrl}`,
        });
      } else if (image.data.length <= IMAGE_DATA_URL_FALLBACK_MAX_CHARS) {
        content.push({
          type: 'text',
          text: `Screenshot ${image.index} data URL:\ndata:${image.mimeType};base64,${image.data}`,
        });
      }

      return content;
    });

    return {
      content: [
        { type: 'text', text: result.text },
        ...imageContent,
      ],
      structuredContent: {
        url: result.url,
        finalUrl: result.finalUrl,
        title: result.title,
        viewportWidth: result.viewportWidth,
        viewportHeight: result.viewportHeight,
        fullPage: result.fullPage,
        pageWidth: result.pageWidth,
        pageHeight: result.pageHeight,
        capturedHeight: result.capturedHeight,
        format: result.format,
        images: imagesWithAssets.map(({ data, ...image }) => image),
        warning: result.warning,
      },
    };
  }),
);

server.registerTool(
  'web_search_and_fetch',
  {
    title: 'Web Search And Fetch',
    description:
      'Search the web and then open the top results in one call. Useful when the model needs a quick research pass without multiple tool calls.',
    inputSchema: {
      query: z.string().min(1).describe('The search query to run.'),
      count: z.coerce
        .number()
        .int()
        .min(1)
        .max(10)
        .optional()
        .describe('How many search results to collect. Default: 5.'),
      openTop: z.coerce
        .number()
        .int()
        .min(1)
        .max(3)
        .optional()
        .describe('How many of the top results to open and read. Default: 3.'),
      maxCharsPerPage: z.coerce
        .number()
        .int()
        .min(1_000)
        .max(20_000)
        .optional()
        .describe('Maximum page text to return per opened result.'),
      site: z.string().optional().describe('Optional domain filter such as "developer.mozilla.org".'),
      countryCode: z
        .string()
        .min(2)
        .max(5)
        .optional()
        .describe('Search market like "us", "gb", or "de". Default: "us".'),
      language: z
        .string()
        .optional()
        .describe('Language hint like "en-US". Default: "en-US".'),
    },
    outputSchema: {
      query: z.string(),
      fullQuery: z.string(),
      backend: z.string(),
      market: z.object({
        countryCode: z.string(),
        language: z.string(),
      }),
      results: z.array(searchResultSchema),
      pages: z.array(pageSchema),
    },
  },
  wrapTool(async (args) => {
    const result = await searchAndFetch(args);
    return {
      content: [{ type: 'text', text: result.text }],
      structuredContent: {
        query: result.query,
        fullQuery: result.fullQuery,
        backend: result.backend,
        market: result.market,
        results: result.results,
        pages: result.pages,
      },
    };
  }),
);

async function publishImageAsset({ base64, mimeType, label }) {
  if (process.env.LM_WEB_MCP_DISABLE_ASSET_SERVER === '1') {
    return null;
  }

  const bytes = Buffer.from(String(base64 ?? ''), 'base64');
  if (bytes.length === 0) {
    return null;
  }

  const serverInfo = await ensureAssetServer();
  if (!serverInfo) {
    return null;
  }

  pruneImageAssets();
  const extension = imageExtension(mimeType);
  const safeLabel = sanitizeAssetLabel(label || 'image');
  const id = `${Date.now()}-${randomUUID()}-${safeLabel}.${extension}`;
  imageAssets.set(id, {
    bytes,
    mimeType: normalizeImageMimeType(mimeType),
    createdAt: Date.now(),
  });

  return `${serverInfo.baseUrl}${ASSET_ROUTE_PREFIX}${encodeURIComponent(id)}`;
}

async function ensureAssetServer() {
  if (assetServerPromise) {
    return assetServerPromise;
  }

  assetServerPromise = new Promise((resolve) => {
    const server = createServer((request, response) => {
      try {
        const requestUrl = new URL(request.url ?? '/', 'http://localhost');
        if (!requestUrl.pathname.startsWith(ASSET_ROUTE_PREFIX)) {
          response.writeHead(404).end('Not found');
          return;
        }

        const id = decodeURIComponent(requestUrl.pathname.slice(ASSET_ROUTE_PREFIX.length));
        const asset = imageAssets.get(id);
        if (!asset || Date.now() - asset.createdAt > ASSET_TTL_MS) {
          imageAssets.delete(id);
          response.writeHead(404).end('Image expired or not found');
          return;
        }

        response.writeHead(200, {
          'content-type': asset.mimeType,
          'content-length': String(asset.bytes.length),
          'cache-control': 'no-store',
          'access-control-allow-origin': '*',
        });
        response.end(asset.bytes);
      } catch (error) {
        response.writeHead(500).end(errorMessage(error));
      }
    });

    server.on('error', (error) => {
      console.error(`Image asset server could not start on port ${ASSET_PORT}: ${errorMessage(error)}`);
      resolve(null);
    });

    server.listen(ASSET_PORT, ASSET_HOST, () => {
      const baseUrl = resolveAssetBaseUrl(ASSET_PORT);
      if (process.env.LM_WEB_MCP_DEBUG === '1') {
        console.error(`local-web-mcp image asset server is listening at ${baseUrl}`);
      }
      resolve({ baseUrl });
    });
  });

  return assetServerPromise;
}

function pruneImageAssets() {
  const now = Date.now();
  for (const [id, asset] of imageAssets.entries()) {
    if (now - asset.createdAt > ASSET_TTL_MS) {
      imageAssets.delete(id);
    }
  }

  while (imageAssets.size > 100) {
    const oldest = imageAssets.keys().next().value;
    if (!oldest) break;
    imageAssets.delete(oldest);
  }
}

function resolveAssetBaseUrl(port) {
  const publicBaseUrl = process.env.LM_WEB_MCP_PUBLIC_BASE_URL;
  if (publicBaseUrl) {
    return publicBaseUrl.replace(/\/+$/, '');
  }

  return `http://${detectLanAddress()}:${port}`;
}

function detectLanAddress() {
  const interfaces = networkInterfaces();
  for (const addresses of Object.values(interfaces)) {
    for (const address of addresses ?? []) {
      if (address.family === 'IPv4' && !address.internal) {
        return address.address;
      }
    }
  }

  return '127.0.0.1';
}

function sanitizeAssetLabel(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48) || 'image';
}

function imageExtension(mimeType) {
  const normalized = normalizeImageMimeType(mimeType);
  if (normalized === 'image/jpeg') return 'jpg';
  if (normalized === 'image/webp') return 'webp';
  return 'png';
}

function normalizeImageMimeType(mimeType) {
  const normalized = String(mimeType ?? '').split(';')[0].trim().toLowerCase();
  if (normalized === 'image/jpg') return 'image/jpeg';
  if (normalized === 'image/jpeg' || normalized === 'image/webp' || normalized === 'image/png') {
    return normalized;
  }
  return 'image/png';
}

function parseInteger(value, fallback) {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function errorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  if (process.env.LM_WEB_MCP_DEBUG === '1') {
    console.error('local-web-mcp is running on stdio');
  }
}

function wrapTool(handler) {
  return async (args) => {
    try {
      return await handler(args);
    } catch (error) {
      const message =
        error instanceof Error ? error.message : String(error);
      console.error('Tool error:', message);
      return {
        isError: true,
        content: [{ type: 'text', text: `Error: ${message}` }],
      };
    }
  };
}

process.on('unhandledRejection', (error) => {
  console.error('Unhandled rejection:', error);
});

process.on('uncaughtException', (error) => {
  console.error('Uncaught exception:', error);
  process.exit(1);
});

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
